class Failure {
  final String message;
  final String error;
  const Failure({required this.error, this.message='An error unexpected occur!'});
}
