class Failure {
  final String message;
  final String error;
  const Failure(
      {this.error = 'Error', this.message = 'An error unexpected occur!'});
}
